In [1]:
a = int(input("A: "))
b = int(input("B: "))
try:
    res = a/b
    print(res)
except:
    print("Not possible")
print("Done!")

A: 12
B: 0
Not possible
Done!


In [29]:
import numpy as np
def accept():
    print("For Matrix 1")
    row = int(input("Enter rows : "))
    col = int(input("Enter columns: "))
    print("For Matrix 2")
    row1 = int(input("Enter rows : "))
    col1 = int(input("Enter columns: "))
    return row,col,row1,col1
def check(row,col,row1,col1):
    try:
        if((row==row1) and (col==col1)):
            return 1
    except:
        print("Not Equal!")
        return 0
def check1(row,col,row1,col1):
    try:
        if((row==col1) and (col==row1)):
            return 1
    except:
        print("Not Equal!")
        return 0
        
def add(M1,M2):
    if(check(row,col,row1,col1)):
            print(M1+M2)
def sub(M1,M2):
    try:
        if(check(row,col,row1,col1)):
            print(M1-M2)
    except:
        print("Not Possible!")
def mult(M1,M2):
     if(check1(row,col,row1,col1)):
        result =np.zeros((row,col1))
        for i in range(0,row):
            for j in range(0,col1):
                for k in range(0,col):
                    result[i][j] += M1[i][k] * M2[k][j]
        print(result)
    
def div(M1,M2):
    M3 =np.zeros((row,col))
    try:
        if(check(row,col,row1,col1)):
            for i in range(0,row):
                for j in range(0,col):
                    M3[i][j] = M1[i][j] / M2[i][j]
                    if(M3==(1/0)):
                        raise ZeroDivisionError
            res = M3
    except ZeroDivisionError:
        print("Division Not Possible!")
    else:
        print(res)
while True:
    row,col,row1,col1=accept()
    if(check(row,col,row1,col1)):
        break
    else:
        row,col,row1,col1=accept()
M1 =np.zeros((row,col))
for i in range(0,row):
    for j in range(0,col):
        M1[i][j] = int(input("M1:"))
M2 =np.zeros((row1,col1))
for i in range(0,row1):
    for j in range(0,col1):
        M2[i][j] = int(input("M2:"))

add(M1,M2)
sub(M1,M2)
mult(M1,M2)
div(M1,M2)

For Matrix 1
Enter rows : 2
Enter columns: 2
For Matrix 2
Enter rows : 2
Enter columns: 2
M1:1
M1:2
M1:3
M1:4
M2:1
M2:0
M2:2
M2:3
[[2. 2.]
 [5. 7.]]
[[0. 2.]
 [1. 1.]]
[[ 5.  6.]
 [11. 12.]]
Division Not Possible!
